In [ ]:
# Task - 1 Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)
import numpy as np
import pandas as pd
s0=pd.Series(np.random.rand(4))
s1=pd.Series(np.random.rand(4))
s2=pd.Series(np.random.rand(4))
s3=pd.Series(np.random.rand(4))
df=pd.DataFrame([s0,s1,s2,s3])
print(df)

          0         1         2         3
0  0.393149  0.175834  0.751040  0.345473
1  0.575771  0.407944  0.158532  0.917130
2  0.699412  0.353707  0.756118  0.406667
3  0.299469  0.618166  0.208259  0.709780

In [ ]:
# Task - 2 Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4'
df.columns=['Random value 1', 'Random value 2', 'Random value 3', 'Random value 4',]
print(df)

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.997821        0.406901        0.709455        0.847288
1        0.404431        0.174371        0.715183        0.896365
2        0.401088        0.608914        0.360086        0.015207
3        0.298098        0.979836        0.238006        0.994749

In [ ]:
# Task - 3 Find the descriptive statistics of the 'df' dataframe.
df.describe()

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.525360        0.542506        0.505682        0.688402
std          0.318818        0.341360        0.243764        0.452966
min          0.298098        0.174371        0.238006        0.015207
25%          0.375341        0.348769        0.329566        0.639268
50%          0.402760        0.507907        0.534770        0.871827
75%          0.552779        0.701644        0.710887        0.920961
max          0.997821        0.979836        0.715183        0.994749

In [ ]:
# Task - 4 Check for the null values in 'df' and find the data type of the columns.
print(df.isnull().sum()) #to check number of null values in columns (at last, dtype tells data type of columns)
print(" ")
print(df.isnull())

Random value 1    0
Random value 2    0
Random value 3    0
Random value 4    0
dtype: int64

   Random value 1  Random value 2  Random value 3  Random value 4
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False

In [ ]:
# Task - 5 Display the 'Random value 2' & 'Random value 3' columns with location method and index location method.

print('LOCATION METHOD')
print(df.loc[:,'Random value 2':'Random value 3'])
print('\nINDEX LOCATION METHOD')
print(df.iloc[:,1:3])

LOCATION METHOD
   Random value 2  Random value 3
0        0.406901        0.709455
1        0.174371        0.715183
2        0.608914        0.360086
3        0.979836        0.238006

INDEX LOCATION METHOD
   Random value 2  Random value 3
0        0.406901        0.709455
1        0.174371        0.715183
2        0.608914        0.360086
3        0.979836        0.238006